### PR TITLE
Enabled `diskstats` collector.

### PR DESCRIPTION
**Pull request by whites11**
Towards https://github.com/giantswarm/roadmap/issues/1093

enabled disk IO metrics

### CODE REVIEW

**Comment by erkanerol** [comment]
As far as I remember, when one of these collectors fails to fetch metrics, we receive an alert :) Let me test this for CAPO tomorrow and share the result here.

**Comment by whites11** [comment]
> As far as I remember, when one of these collectors fails to fetch metrics, we receive an alert :) Let me test this for CAPO tomorrow and share the result here.

any news?

**Comment by erkanerol** [comment]
@whites11 SORRYYYYYYY. CHECKING.

**Comment by erkanerol** [comment]
Screen Shot 2022-05-27 at 15 29 52

I also verified that the metrics here have some meaningful values https://github.com/prometheus/node_exporter/blob/0aec4076660fded7d5c34c53aa9ac79f131cc7de/collector/diskstats_linux_test.go

**Comment by whites11** [comment]
> Screen Shot 2022-05-27 at 15 29 52
> 
> I also verified that the metrics here have some meaningful values https://github.com/prometheus/node_exporter/blob/0aec4076660fded7d5c34c53aa9ac79f131cc7de/collector/diskstats_linux_test.go

Thanks, can you please approve the PR, then!

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
