### PR TITLE
Fix collector systemd

### PR DESCRIPTION
**Pull request by marieroque**
towards https://github.com/giantswarm/giantswarm/issues/25217

Since v1.14.1, node-exporter has errors on collector `systemd`

----------------------------------------------------------------------------------------------------------------

TESTING:

Before deploying the new version, 
- [ ] Check `node-exporter` logs and see:
```
ts=2023-01-06T14:35:22.613Z caller=collector.go:169 level=error msg="collector failed" name=systemd duration_seconds=0.004798513 err="couldn't get dbus connection: An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\"(null)\" (inactive) interface=\"org.freedesktop.DBus\" member=\"Hello\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.DBus\" (bus)"
```

Then, deploy the new version and 
- [ ] Verify logs

### CODE REVIEW

**Comment by marieroque** [comment]
@giantswarm/team-shield 
Please can you give us your opinion on this PR ?

To avoid issue with collector systemd, we had to annotate the pods:
`container.apparmor.security.beta.kubernetes.io/node-exporter: "unconfined"`

see https://github.com/prometheus-community/helm-charts/issues/2304#issuecomment-1221477422

**Comment by fhielpos** [comment]
Is this an issue in Flatcar and CAPI? 

For now I would say it's okay to set the profile as unconfined. Probably we can also create a profile just for node exporter in the future.

**Review by fhielpos — APPROVED** [review]

**Comment by hervenicol** [comment]
> Is this an issue in Flatcar and CAPI?

We honestly don't understand where the issue comes from.
With node-collector-app 1.13.0 it works well, but we got these errors on `guppy` when upgrading to 1.14.
We played a bit with the PSPs with no success, and the easiest way to fix the app was this annotation.

**Comment by QuentinBisson** [comment]
What's weird is that app armor is not enabled unless CAPVCD has it by default?

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Approving still as long as this was tested on both AppArmor and non AppArmor installations :)

**Pull request merged**
